export default {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_FAIL: 'GET_MOVIES_FAIL',

  SEARCH_MOVIES: 'SEARCH_MOVIES',
  SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
  SEARCH_MOVIES_FAIL: 'SEARCH_MOVIES_FAIL',
};
