export default {
  GET_MOVIE: 'GET_MOVIE',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_FAIL: 'GET_MOVIE_FAIL',

  GET_MOVIE_CREDITS: 'GET_MOVIE_CREDITS',
  GET_MOVIE_CREDITS_SUCCESS: 'GET_MOVIE_CREDITS_SUCCESS',
  GET_MOVIE_CREDITS_FAIL: 'GET_MOVIE_CREDITS_FAIL',
};
