export default {
  GET_MOVIE: 'GET_MOVIE',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_FAIL: 'GET_MOVIE_FAIL',

  GET_MOVIE_CREDITS: 'GET_MOVIE_CREDITS',
  GET_MOVIE_CREDITS_SUCCESS: 'GET_MOVIE_CREDITS_SUCCESS',
  GET_MOVIE_CREDITS_FAIL: 'GET_MOVIE_CREDITS_FAIL',

  GET_MOVIE_IMAGES: 'GET_MOVIE_IMAGES',
  GET_MOVIE_IMAGES_SUCCESS: 'GET_MOVIE_IMAGES_SUCCESS',
  GET_MOVIE_IMAGES_FAIL: 'GET_MOVIE_IMAGES_FAIL',

  GET_MOVIE_RECOMMENDATIONS: 'GET_MOVIE_RECOMMENDATIONS',
  GET_MOVIE_RECOMMENDATIONS_SUCCESS: 'GET_MOVIE_RECOMMENDATIONS_SUCCESS',
  GET_MOVIE_RECOMMENDATIONS_FAIL: 'GET_MOVIE_RECOMMENDATIONS_FAIL',
};
